var database_en = [
	{id:"AuX7nPBqDts", title: "Basic addition"},
	{id:"aNqG4ChKShI", title: "Basic subtraction"},
	{id:"b22tMEc6Kko", title: "Example: Adding two digit numbers (no carrying)"},
	{id:"incKJchBCLo", title: "Subtraction 2"},
	{id:"sAw71J2kYJE", title: "Example: 2-digit subtraction (no borrowing)"},
	{id:"27Kp7HJYj2c", title: "Level 2 addition"},
	{id:"Wm0zq-NqEFs", title: "Carrying when adding three digit numbers"},
	{id:"O9zSHs1TWMM", title: "Why carrying works"},
	{id:"9hM32lsQ4aI", title: "Examples of carrying when adding three digit numbers"},
	{id:"fOXo4p4WDKM", title: "Addition 4"},
	{id:"9T3AAn-Cw3g", title: "Basic regrouping or borrowing when subtracting three digit numbers"},
	{id:"QOtam19NQcQ", title: "Regrouping when subtracting three digit numbers"},
	{id:"LSaaKau63Gg", title: "Regrouping twice when subtracting three digit numbers"},
	{id:"3lHBgFvr3yE", title: "Regrouping from 0 when subtracting three digit numbers"},
	{id:"RRk5qLd__Ro", title: "Borrowing once example 1"},
	{id:"8_fT1BsTmt4", title: "Borrowing once example 2"},
	{id:"OJ-wajo6oa4", title: "Regrouping (borrowing) twice example"},
	{id:"GBtcGO44e-A", title: "Alternate mental subtraction method"},
	{id:"QY8vv7eVVJE", title: "Subtraction word problem"},
	{id:"RNxwasijbAo", title: "Intro to multiplication"},
	{id:"cDpBtkU2cf8", title: "Multiplication as groups of objects"},
	{id:"vfMx9-rJXuo", title: "More on the concept of multiplication"},
	{id:"QI6x0KNxiCs", title: "The idea of division"},
	{id:"ez1MIB8_2O0", title: "Number line 1"},
	{id:"mvOkMYCygps", title: "Basic multiplication"},
	{id:"xO_1bYgoQvA", title: "Multiplication 2: The multiplication tables"},
	{id:"Yw3EoxC_GXU", title: "Example: Ways to represent multiplication"},
	{id:"qihoczo1Ujk", title: "Multiplication 3: 10,11,12 times tables"},
	{id:"MTzTqvzWzm8", title: "Division 1"},
	{id:"4I9iibPLdBw", title: "Example: Expressing division in multiple ways"},
	{id:"OCwLwaAQlMA", title: "Comparing with multiplication exercise"},
	{id:"bS6EmYzpou4", title: "Comparing ages"},
	{id:"fZtUn_THXnk", title: "Multiplication word problem example 1"},
	{id:"Z3qRkxzmYnU", title: "Division word problem example 1"},
	{id:"9CZfG3r5JBE", title: "Comparing magic strength"},
	{id:"jb8mFpA1YI8", title: "Multiplying by multiples of 10"},
	{id:"k68CPfcehTE", title: "2 digit times 1 digit example (no carrying)"},
	{id:"4BtXvopHXI8", title: "3 digit times 1 digit example (no carrying)"},
	{id:"SfxULALs_u8", title: "2 digit times 1 digit example"},
	{id:"TqRReFvbpXA", title: "3 digit times 1 digit example"},
	{id:"twMdew4Zs8Q", title: "4 digit times 1 digit example"},
	{id:"t8m0NalQtEk", title: "2-digit times a 2-digit number"},
	{id:"0WUXQNjdRvM", title: "Example: 2-digit times 2-digit"},
	{id:"-h3Oqhl8fPg", title: "Multiple digit numbers"},
	{id:"tx2Niw7aJJ8", title: "Multiplication estimation example"},
	{id:"_k3aWF6_b4w", title: "Multiplication 7: Old video giving more examples"},
	{id:"8Ft5iHhauJ0", title: "Introduction to long division"},
	{id:"BIGX05Mp5nw", title: "Introduction to remainders"},
	{id:"MbpmP1esh-Q", title: "Long division with remainder example"},
	{id:"NcADzGz3bSI", title: "More long division without and with remainders"},
	{id:"xXIG8ouHcsc", title: "Dividing by a two digit number"},
	{id:"gHTH6PKfpMc", title: "Level 4 division"},
	{id:"gS6TfWUv97I", title: "Lattice multiplication"},
	{id:"S3z4XqC_YSc", title: "Why lattice multiplication works"},
	{id:"R486L0M5cWk", title: "Partial quotient method of division"},
	{id:"omFelSZvaJc", title: "Partial quotient method of division 2"},
	{id:"anlOhNHlqwg", title: "Multi step word problems with whole numbers exercise 1"},
	{id:"cTveNRjWQYo", title: "Multi step word problems with whole numbers exercise 2"},
	{id:"l7h8A6SX5kY", title: "Multi step word problems with whole numbers exercise 3"},
	{id:"p0jCw2sqZgs", title: "Understanding multiplication through area models"},
	{id:"vbGwcvXgDlg", title: "Area model for multiplication"},
	{id:"Df9h5t64NlQ", title: "Divisibility tests for 2, 3, 4, 5, 6, 9, 10"},
	{id:"2G_Jr_XpnY4", title: "Recognizing divisibility"},
	{id:"NehkLV77ITk", title: "The why of the 3 divisibility rule"},
	{id:"XAzFGx3Ruig", title: "The why of the 9 divisibility rule"},
	{id:"vcn2ruTOwFo", title: "Finding factors of a number"},
	{id:"5xe-6GPR_qQ", title: "Finding factors and multiples"},
	{id:"AHRh3EpJQH0", title: "Divisibility intuition"}
];

var database_fr = [
	{id:"7CKiA8d_x2U", title:" Les bases de l'addition ", local: true},
	{id:"Val2O1rLC44", title:" Les bases de la soustraction ", local: true},
	{id:"inm7J2V_CF0", title:" Exemple d'addition sans retenue "},
	{id:"gDnTQ2VROoI", title:"Comprendre la soustraction"},
	{id:"qhTqJbaeJ9Q", title:"Exemple de soustraction sans retenue"},
	{id:"BcVYZ3OsShU", title:"Addition : Introduction à la retenue"},
	{id:"BykCNzqHGDU", title:"Additions de nombres à 4 chiffres"},
	{id:"p4Rqs_vWu-M", title:"Soustraction avec retenue - Exemple 1"},
	{id:"F4jwP0VQe6Q", title:"Soustraction avec retenue - Exemple 2"},
	{id:"j_gfuaJluuY", title:"Soustraction avec retenue - Exemple 3"},
	{id:"V8sPoUAt1NI", title:" Méthode alternative pour la soustraction de tête "},
	{id:"XmkhQY3gpM8", title:"La droite numérique graduée"},
	{id:"MPv-3QxFBhk", title:"Les bases de la multiplication"},
	{id:"hIw-cwvybVM", title:"Tables de multiplication"},
	{id:"KsGYn1D0nr0", title:"Différentes façons d'écrire la multiplication"},
	{id:"n4HNA9b6Y4I", title:" Tables de multiplication de 10, de 11 et de 12 "},
	{id:"N-NmGG-t0eg", title:"Les bases de la division"},
	{id:"_ZSdGlAi4Vg", title:"Différentes façons d'écrire la division"}
];

var database_es = [
	{id:"yHeTx8SAaOQ", title: "Sumas básicas", local: true},
	{id:"CIljE0sQRV8", title: "Restas básicas"},
	{id:"vrjBZsP1ENk", title: "Sumando números de dos dígitos (sin llevada). Ejemplo"},
	{id:"gyh_9uPdDEg", title: "Restas 2"},
	{id:"DHIQ2DEf_ho", title: "Restando números de dos dígitos (sin pedir prestado). Ejemplo"},
	{id:"qlP585OyE4Q", title: "Sumas nivel 2"},
	{id:"Zrjb5wPlqoU", title: "Carrying when adding three digit numbers"},
	{id:"cVSuEsR_xyI", title: "Why carrying works"},
	{id:"xjpvHCBdZOI", title: "Examples of carrying when adding three digit numbers"},
	{id:"cyBTtJYD6Ds", title: "Sumas 4"},
	{id:"xCEQRQeWHC4", title: "Basic regrouping or borrowing when subtracting three digit numbers"},
	{id:"j84hRaBH_Zs", title: "Regrouping when subtracting three digit numbers"},
	{id:"p341ietbG_4", title: "Regrouping twice when subtracting three digit numbers"},
	{id:"2WNv6kxjCWU", title: "Regrouping from 0 when subtracting three digit numbers"},
	{id:"EyEae0FCTYM", title: "Pidiendo prestado una vez. Ejemplo 1"},
	{id:"KWbJl7PD4Bg", title: "Pidiendo prestado una vez. Ejemplo 2"},
	{id:"3MzESVgtDuo", title: "Reagrupando (pedir prestado) dos veces. Ejemplo"},
	{id:"VluzHOAOSDs", title: "Cómo resto en mi cabeza"},
	{id:"G4Uz3EcXV5M", title: "Introducción a la multiplicación"},
	{id:"NAejUfwVooU", title: "La multiplicación vista como grupos de objetos"},
	{id:"w61xGdfhK3k", title: "Más sobre el concepto de multiplicación"},
	{id:"TBz0sJMpaTE", title: "La idea de la división"}
];