var database_fr = [
	{id:"7CKiA8d_x2U", title:" Les bases de l'addition ", local: true},
	{id:"Val2O1rLC44", title:" Les bases de la soustraction ", local: true},
	{id:"inm7J2V_CF0", title:" Exemple d'addition sans retenue "},
	{id:"gDnTQ2VROoI", title:"Comprendre la soustraction"},
	{id:"qhTqJbaeJ9Q", title:"Exemple de soustraction sans retenue"},
	{id:"BcVYZ3OsShU", title:"Addition : Introduction à la retenue"},
	{id:"BykCNzqHGDU", title:"Additions de nombres à 4 chiffres"},
	{id:"p4Rqs_vWu-M", title:"Soustraction avec retenue - Exemple 1"},
	{id:"F4jwP0VQe6Q", title:"Soustraction avec retenue - Exemple 2"},
	{id:"j_gfuaJluuY", title:"Soustraction avec retenue - Exemple 3"},
	{id:"V8sPoUAt1NI", title:" Méthode alternative pour la soustraction de tête "},
	{id:"XmkhQY3gpM8", title:"La droite numérique graduée"},
	{id:"MPv-3QxFBhk", title:"Les bases de la multiplication"},
	{id:"hIw-cwvybVM", title:"Tables de multiplication"},
	{id:"KsGYn1D0nr0", title:"Différentes façons d'écrire la multiplication"},
	{id:"n4HNA9b6Y4I", title:" Tables de multiplication de 10, de 11 et de 12 "},
	{id:"N-NmGG-t0eg", title:"Les bases de la division"},
	{id:"_ZSdGlAi4Vg", title:"Différentes façons d'écrire la division"}
];

var database_es = [
	{id:"yHeTx8SAaOQ", title: "Sumas básicas", local: true},
	{id:"CIljE0sQRV8", title: "Restas básicas"},
	{id:"vrjBZsP1ENk", title: "Sumando números de dos dígitos (sin llevada). Ejemplo"},
	{id:"gyh_9uPdDEg", title: "Restas 2"},
	{id:"DHIQ2DEf_ho", title: "Restando números de dos dígitos (sin pedir prestado). Ejemplo"},
	{id:"qlP585OyE4Q", title: "Sumas nivel 2"},
	{id:"Zrjb5wPlqoU", title: "Carrying when adding three digit numbers"},
	{id:"cVSuEsR_xyI", title: "Why carrying works"},
	{id:"xjpvHCBdZOI", title: "Examples of carrying when adding three digit numbers"},
	{id:"cyBTtJYD6Ds", title: "Sumas 4"},
	{id:"xCEQRQeWHC4", title: "Basic regrouping or borrowing when subtracting three digit numbers"},
	{id:"j84hRaBH_Zs", title: "Regrouping when subtracting three digit numbers"},
	{id:"p341ietbG_4", title: "Regrouping twice when subtracting three digit numbers"},
	{id:"2WNv6kxjCWU", title: "Regrouping from 0 when subtracting three digit numbers"},
	{id:"EyEae0FCTYM", title: "Pidiendo prestado una vez. Ejemplo 1"},
	{id:"KWbJl7PD4Bg", title: "Pidiendo prestado una vez. Ejemplo 2"},
	{id:"3MzESVgtDuo", title: "Reagrupando (pedir prestado) dos veces. Ejemplo"},
	{id:"VluzHOAOSDs", title: "Cómo resto en mi cabeza"},
	{id:"G4Uz3EcXV5M", title: "Introducción a la multiplicación"},
	{id:"NAejUfwVooU", title: "La multiplicación vista como grupos de objetos"},
	{id:"w61xGdfhK3k", title: "Más sobre el concepto de multiplicación"},
	{id:"TBz0sJMpaTE", title: "La idea de la división"}
];